theme = "Catppuccin-mocha"
client_id = ""
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
track_table_item_max_len = 32
default_device = "spotify-player"

[device]
name = "spotify-player"
device_type = "speaker"
volume = 100
bitrate = 160
audio_cache = false
