#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#if path to liblinkt is not not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# start eww daemon
eww daemon &

# Boot picom or compton if it exists
picom --experimental-backends --config ~/.config/picom/picom.conf &> /dev/null &
# picom --experimental-backends --config ~/Pobrane/bspdots-main/config/picom/picom.conf &> /dev/null &

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# set background
nitrogen --restore

# run polkit deamon
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# set pl keyboard
setxkbmap -layout pl

# set touchpad (for Lenovo laptop)
xinput set-prop "ETPS/2 Elantech Touchpad" "libinput Tapping Enabled" 1

# Locksreen
xidlehook \
	--not-when-fullscreen \
	--not-when-audio \
	--timer 600 \
		'$HOME/.config/qtile/scripts/lock.sh' \
		'' \
	--timer 300 \
		'systemctl suspend' \
		'' &

#open eww 'bar' windows
#this is a bit of an uggly hack, a more elegant way will hopefully be possible with a future `eww` version
sleep 1
index=0
sizes=( $(leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' ) )
for size in "${sizes[@]}"
do
  eww open bar
  eww close bar
  eww open bar
  let index=index+1
done
