[theme]
background = "background"
primary = "foreground"
secondary = "magenta"
title = "#F8BD96"
playing = "#111111"
playing_selected = "light green"
playing_bg = "green"
highlight = "#111111"
highlight_bg = "#c4cbff"
error = "light white"
error_bg = "red"
statusbar = "#111111"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"
