[theme]
background = "default"
primary = "#D9E0EE"
secondary = "#default"
title = "#F8BD96"
playing = "#1E1E2E"
playing_selected = "#1E1E2E"
playing_bg = "#ABE9B3"
highlight = "#1E1E2E"
highlight_bg = "#C9CBFF"
error = "#D9E0EE"
error_bg = "#F28FAD"
statusbar = "#1E1E2E"
statusbar_progress = "#ABE9B3"
statusbar_bg = "#ABE9B3"
cmdline = "#D9E0EE"
cmdline_bg = "1E1E2E"
search_match = "#96CDFB"
