# Elkrien

spacing         = 3
hide_ascii      = false
key_color       = "Green"
separator       = ""
separator_color = "Red"
padding         = 0

[randomize]
key_color       = false

[box]
border          = "rounded"
visible         = true

[palette]
glyph           = "  "
visible         = true

[bar]
glyph           = "●"
hide_delimiters = true
visible         = false

[box.inner_margin]
x               = 5
y               = 2

[custom_ascii]
# color           = "#cba6f7"
path            = "~/.config/macchina/themes/nobara_logo"
