### Modkey and tags
modkey = "Mod4"
workspaces = []
tags = ["", "", "", "", "", "", "", "", ""]

### Tag Behaviour
# disable_current_tag_swap = true

### Focus behaviour
focus_behaviour = "Sloppy" #"Driven" #"ClickTo"
focus_new_windows = true

### Scratchpads
[[scratchpad]]
name = "terminal-scratchpad"
value = "alacritty"
x = 350
y = 250
height = 600
width = 1200

[[scratchpad]]
name = "cli-filemanager"
value = "alacritty -e ranger"
x = 350
y = 250
height = 600
width = 1200

[[scratchpad]]
name = "filemanager"
value = "nemo"
x = 350
y = 250
height = 600
width = 1200

[[scratchpad]]
name = "spotify"
value = "alacritty -e spotify_player"
x = 350
y = 250
height = 600
width = 1200

[[scratchpad]]
name = "radio"
value = "alacritty -e pyradio"
x = 350
y = 250
height = 600
width = 1200

### Keybindings

# Open terminal in scratchpad
[[keybind]]
command = "ToggleScratchPad"
value = "terminal-scratchpad" # Name set for the scratchpad
modifier = ["modkey", "Shift"]
key = "Return"

# Open Ranger in scratchpad
[[keybind]]
command = "ToggleScratchPad"
value = "cli-filemanager"
modifier = ["modkey", "Control"]
key = "e"

# Open Nemo in scratchpad
[[keybind]]
command = "ToggleScratchPad"
value = "filemanager"
modifier = ["modkey", "Shift"]
key = "e"

# Open Spotify in scratchpad
[[keybind]]
command = "ToggleScratchPad"
value = "spotify"
modifier = ["modkey", "Shift"]
key = "a"

# Open Radio in scratchpad
[[keybind]]
command = "ToggleScratchPad"
value = "radio"
modifier = ["modkey"]
key = "a"

# Applications launcher (rofi)
[[keybind]]
command = "Execute"
value = "rofi -no-config -no-lazy-grab -show drun -theme ~/.config/rofi/launcher.rasi"
modifier = ["modkey", "Shift"]
key = "r"

# Applications launcher (rofi full screen)
[[keybind]]
command = "Execute"
value = "rofi -no-config -no-lazy-grab -show drun -theme ~/.config/rofi/small-launcher-alt.rasi"
modifier = ["modkey"]
key = "r"

# Open Terminal (alacritty)
[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey"]
key = "Return"

# PowerMenu
[[keybind]]
command = "Execute"
value = "~/.config/rofi/powermenu.sh"
modifier = ["modkey"]
key = "p"

# Open File Explorer (Nemo)
[[keybind]]
command = "Execute"
value = "nemo"
modifier = ["modkey"]
key = "e"

# Open Visual Code
[[keybind]]
command = "Execute"
value = "code"
modifier = ["modkey"]
key = "v"

# Open Web Browser (Microsoft Edge)
[[keybind]]
command = "Execute"
value = "microsoft-edge-stable"
modifier = ["modkey"]
key = "w"

# Open Mail Client (Maispring)
[[keybind]]
command = "Execute"
value = "mailspring"
modifier = ["modkey"]
key = "m"

# Open Dashboard
[[keybind]]
command = "Execute"
value = "eww open --toggle dashboard-resources-window"
modifier = ["modkey"]
key = "d"

# Screenshot 
[[keybind]]
command = "Execute"
value = "eww open --toggle takeshot"
modifier = ["modkey"]
key = "s"

# Screencast
[[keybind]]
command = "Execute"
value = "simplescreenrecorder"
modifier = ["modkey", "Shift"]
key = "s"

# Windows switcher
[[keybind]]
command = "Execute"
value = "rofi -show window -theme ~/.config/rofi/windows-alt.rasi"
modifier = ["Alt"]
key = "Tab"

# Theme Switcher
[[keybind]]
command = "Execute"
value = "eww open --toggle themes-window"
modifier = ["modkey"]
key = "t"

# VolumeUp +5%
[[keybind]]
command = "Execute"
value = "~/.config/leftwm/themes/catppuccin_eww/scripts/volume.sh +5%"
key = "XF86XK_AudioRaiseVolume"

# VolumeUp +1%
[[keybind]]
command = "Execute"
value = "~/.config/leftwm/themes/catppuccin_eww/scripts/volume.sh +1%"
modifier = ["Shift"]
key = "XF86XK_AudioRaiseVolume"

# VolumeDown -5%
[[keybind]]
command = "Execute"
value = "~/.config/leftwm/themes/catppuccin_eww/scripts/volume.sh -5%"
key = "XF86XK_AudioLowerVolume"

# VolumeDown -1%
[[keybind]]
command = "Execute"
value = "~/.config/leftwm/themes/catppuccin_eww/scripts/volume.sh -1%"
modifier = ["Shift"]
key = "XF86XK_AudioLowerVolume"

# VolumeMute Toggle
[[keybind]]
command = "Execute"
value = "~/.config/leftwm/themes/catppuccin_eww/scripts/volume.sh toggle"
key = "XF86XK_AudioMute"

# BrightnessUp +5%
[[keybind]]
command = "Execute"
value = "~/.config/leftwm/themes/catppuccin_eww/scripts/brightness.sh +5%"
key = "XF86XK_MonBrightnessUp"

# BrightnessUp +1%
[[keybind]]
command = "Execute"
value = "~/.config/leftwm/themes/catppuccin_eww/scripts/brightness.sh +1%"
modifier = ["Shift"]
key = "XF86XK_MonBrightnessUp"

# BrightnessDown -5%
[[keybind]]
command = "Execute"
value = "~/.config/leftwm/themes/catppuccin_eww/scripts/brightness.sh 5%-"
key = "XF86XK_MonBrightnessDown"

# BrightnessDown -1%
[[keybind]]
command = "Execute"
value = "~/.config/leftwm/themes/catppuccin_eww/scripts/brightness.sh 1%-"
modifier = ["Shift"]
key = "XF86XK_MonBrightnessDown"

# Toggle Full Screen
[[keybind]]
command = "Execute"
value = "leftwm-command ToggleFullScreen"
modifier = ["modkey"]
key = "f"

# Close Active Window
[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "q"

# Close Active Window
[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "q"

# Reload LeftWM (soft)
[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Control"]
key = "r"

# Move to last Workspace
[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

# Swap Tags
[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "b"

# Move active window up
[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

# Move active window down
[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

# Move active window up
[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

# Move active window down
[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

# Focus active window up
[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

# Focus active window down
[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

# Change layout (next)
[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

# Change layout (previous)
[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Shift"]
key = "space"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

# Focus next workspace
[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"

# Focus previous workspace
[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

# Focus next tag
[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Down"

# Focus previous tag
[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "Up"

# Swap screens left
[[keybind]]
command = "Execute"
value = "leftwm-command SwapScreens"
modifier = ["modkey"]
key = "Left"

# Swap screens right
[[keybind]]
command = "Execute"
value = "leftwm-command SwapScreens"
modifier = ["modkey"]
key = "Right"

# Move active window to next workspace (left)
[[keybind]]
command = "MoveWindowToNextWorkspace"
modifier = ["modkey", "Shift"]
key = "Left"

# Move active window to next workspace (right)
[[keybind]]
command = "MoveWindowToNextWorkspace"
modifier = ["modkey", "Shift"]
key = "Right"

# Increase and decrease window size 
[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey", "Control"]
key = "k"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey", "Control"]
key = "j"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Control", "Alt"]
key = "Left"

[[keybind]]
command = "FocusNextTag"
modifier = ["Control", "Alt"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Control", "Alt"]
key = "Up"

[[keybind]]
command = "FocusNextTag"
modifier = ["Control", "Alt"]
key = "Down"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey", "Shift"]
key = "Tab"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 1\" \"SendWorkspaceToTag 0 0\""
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 2\" \"SendWorkspaceToTag 0 1\""
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 3\" \"SendWorkspaceToTag 0 2\""
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 4\" \"SendWorkspaceToTag 0 3\""
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 5\" \"SendWorkspaceToTag 0 4\""
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 6\" \"SendWorkspaceToTag 0 5\""
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 7\" \"SendWorkspaceToTag 0 6\""
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 8\" \"SendWorkspaceToTag 0 7\""
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 9\" \"SendWorkspaceToTag 0 8\""
modifier = ["modkey", "Shift"]
key = "9"

# Lock screen
[[keybind]]
command = "Execute"
value = "~/.config/eww/scripts/lock.sh"
modifier = ["modkey", "Shift", "Control"]
key = "l"

# Shutdown computer
[[keybind]]
command = "Execute"
value = "shutdown now"
modifier = ["modkey", "Control"]
key = "q"

# Show hotkeys
[[keybind]]
command = "Execute"
value = "~/.config/eww/scripts/keys.sh"
modifier = ["modkey"]
key = "k"

