modkey = "Mod4"
workspaces = []
tags = ["", "", "", "", "", "", "", "", ""]

# Tag Behaviour
# disable_current_tag_swap = true

# Focus behaviour
focus_behaviour = "Sloppy" #"Driven" #"ClickTo"
focus_new_windows = true

# Scratchpads
[[scratchpad]]
name = "Alacritty-scratchpad"
value = "alacritty"
x = 350
y = 250
height = 600
width = 1200

[[scratchpad]]
name = "ranger"
value = "alacritty -e ranger"
x = 350
y = 250
height = 600
width = 1200

[[scratchpad]]
name = "spotify"
value = "alacritty -e ncspot"
x = 350
y = 250
height = 600
width = 1200

[[scratchpad]]
name = "radio"
value = "alacritty -e pyradio"
x = 350
y = 250
height = 600
width = 1200

# Keybindings
[[keybind]]
command = "ToggleScratchPad"
value = "Alacritty-scratchpad" # Name set for the scratchpad
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "ToggleScratchPad"
value = "ranger"
modifier = ["modkey", "Shift"]
key = "e"

[[keybind]]
command = "ToggleScratchPad"
value = "spotify"
modifier = ["modkey", "Shift"]
key = "a"

[[keybind]]
command = "ToggleScratchPad"
value = "radio"
modifier = ["modkey"]
key = "a"

[[keybind]]
command = "Execute"
value ="rofi -no-config -no-lazy-grab -show drun -theme ~/.config/rofi/small-launcher-alt.rasi" 
modifier = ["modkey"]
key = "r"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "Execute"
value = "~/.config/qtile/scripts/powermenu.sh"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "nemo"
modifier = ["modkey"]
key = "e"

[[keybind]]
command = "Execute"
value = "code"
modifier = ["modkey"]
key = "v"

[[keybind]]
command = "Execute"
value = "microsoft-edge-stable"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "Execute"
value = "mailspring"
modifier = ["modkey"]
key = "m"

[[keybind]]
command = "Execute"
value = "flameshot gui"
modifier = ["modkey"]
key = "s"

[[keybind]]
command = "Execute"
value = "rofi -show window -theme ~/.config/rofi/windows-alt.rasi"
modifier = ["Alt"]
key = "Tab"

[[keybind]]
command = "Execute"
value = "~/.config/qtile/scripts/keys.sh"
modifier = ["modkey"]
key = "t"

[[keybind]]
command = "Execute"
value = "~/.config/qtile/scripts/rofi-screenshot"
modifier = ["modkey", "Shift"]
key = "s"

[[keybind]]
command = "Execute"
value = "leftwm-command ToggleFullScreen"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "b"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Shift"]
key = "space"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "Execute"
value = "leftwm-command SwapScreens"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "Execute"
value = "leftwm-command SwapScreens"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "MoveWindowToNextWorkspace"
modifier = ["modkey","Shift"]
key = "Left"

[[keybind]]
command = "MoveWindowToNextWorkspace"
modifier = ["modkey","Shift"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Control","Alt"]
key = "Left"

[[keybind]]
command = "FocusNextTag"
modifier = ["Control", "Alt"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Control","Alt"]
key = "Up"

[[keybind]]
command = "FocusNextTag"
modifier = ["Control", "Alt"]
key = "Down"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey", "Shift"]
key = "Tab"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 1\" \"SendWorkspaceToTag 0 0\""
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 2\" \"SendWorkspaceToTag 0 1\""
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 3\" \"SendWorkspaceToTag 0 2\""
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 4\" \"SendWorkspaceToTag 0 3\""
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 5\" \"SendWorkspaceToTag 0 4\""
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 6\" \"SendWorkspaceToTag 0 5\""
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 7\" \"SendWorkspaceToTag 0 6\""
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 8\" \"SendWorkspaceToTag 0 7\""
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 9\" \"SendWorkspaceToTag 0 8\""
modifier = ["modkey", "Shift"]
key = "9"
