# Catppuccin
# Author : elkrien <elkrien@gmail.com>

"type" = { fg = "yellow" }
"constructor" = { fg = "lavender" }
"constant" = { fg = "peach" }
"constant.character" = { fg = "teal" }
"constant.numeric" = { fg = "peach" }
"constant.builtin" = { fg = "peach" }
"constant.builtin.boolean" = { fg = "peach" }
"string" = { fg = "green" }
"string.regexp" = { fg = "peach" }
"comment" = { fg = "gray" }
"variable" = { fg = "peach" }
"variable.function" = { fg = "blue", modifiers = ["italic"] }
"variable.parameter" = { fg = "rosewater", modifiers = ["italic"] }
"variable.other" = { fg = "rosewater", modifiers = ["italic"] }
"variable.other.member" = { fg = "blue" }
"variable.builtin" = { fg = "teal" }
"punctuation" = { fg = "teal" }
"punctuation.delimeter" = { fg = "teal" }
"punctuation.bracket" = { fg = "gray1" }
"keyword" = { fg = "pink" }
"keyword.control.conditional" = { fg = "red" }
"keyword.control.repeat" = { fg = "red" }
"keyword.control.return" = { fg = "pink" }
"keyword.operator" = { fg = "sky", modifiers = ["bold"] }
"keyword.control.import" = { fg = "teal", modifiers = ["italic"] }
"keyword.function" = { fg = "maroon", modifiers = ["italic"] }
"operator" = { fg = "sky", modifiers = ["bold"] }
"function" = { fg = "blue" }
"function.builtin" = { fg = "peach", modifiers = ["italic"] }
"function.macro" = { fg = "red" }
"tag" = { fg = "peach" }
"namespace" = { fg = "rosewater" }
"markup.heading" = { fg = "blue", modifiers = ["bold"] }
"markup.bold" = { fg = "maroon", modifiers = ["bold"] }
"markup.italic" = { fg = "maroon", modifiers = ["italic"] }
"markup.quote" = { fg = "teal", modifiers = ["italic"] }
"markup.raw" = { fg = "teal", modifiers = ["italic"] }
"markup.link.url" = { fg = "rosewater", modifiers = ["italic", "underlined"] }
"markup.link.text" = { fg = "lavender", modifiers = ["bold"] }
"markup.list" = { fg = "blue" }
"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "yellow" }
"diff.minus" = { fg = "red" }


"ui.background" = { fg = "white", bg = "black2" }
"ui.cursor" =  { fg = "black", bg = "white", modifiers = ["dim"] }
#"ui.selection" = { bg = "red" }
#"ui.cursor.select" = { bg = "gray" }
"ui.cursor.match" = { fg = "peach", modifiers = ["bold", "underlined"] }
#"ui.cursor.primary" = { fg = "black", bg = "white", modifier = ["dim"] }
"ui.help" = { fg = "rosewater", bg = "black1" }
"ui.linenr" = { fg = "black4" }
"ui.linenr.selected" = { fg = "green" }
#"ui.menu" = { fg = "white", bg = "black1" }
"ui.menu.selected" = { fg = "white", bg = "black3" }
#"ui.popup" = { fg = "white", bg = "black3" }
"ui.selection" = { bg = "black4" }
#"ui.selection.primary" = { bg = "gray2" }
"ui.statusline" = { fg = "rosewater", bg = "black1" }
"ui.statusline.inactive" = { fg = "lavender", bg = "black1" }
"ui.text" = { fg = "white" }
"ui.text.focus" = { fg = "lavender" }
"ui.window" = { fg = "white" }

"error" = { fg = "red", modifiers = ["bold"] }
"warning" = { fg = "yellow" }

[palette]
black = "#161320"
black1 = "#1A1826"
black2 = "#1E1E2E"
black3 = "#302D41"
black4 = "#575263"
white = "#D9E0EE"
gray = "#6E6C7E"
gray1 = "#988BA2"
gray2 = "#C3BAC6"
red = "#F28FAD"
peach = "#F8BD96"
yellow = "#FAE3B0"
green = "#ABE9B3"
mauve = "#DDB6F2"
blue = "#96CDFB"
pink = "#F5C2E7"
flamingo = "#F2CDCD"
maroon = "#E8A2AF"
teal = "#B5E8E0"
sky = "#89DCEB"
lavender = "#C9CBFF"
rosewater = "#F5E0DC"

